apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote
  labels:
    app: vote
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
        - name: vote
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
          env:
            - name: REDIS_HOST
              value: "{{ .Values.env.REDIS_HOST }}"
            - name: POSTGRES_HOST
              value: "{{ .Values.env.POSTGRES_HOST }}"
          volumeMounts:
            - name: efs-volume
              mountPath: /efs-data
      volumes:
        - name: efs-volume
          persistentVolumeClaim:
            claimName: vote-efs-pvc
