apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
      - name: vote
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 80
        env:
        - name: REDIS_HOST
          value: "{{ .Values.env.REDIS_HOST }}"
        - name: POSTGRES_HOST
          value: "{{ .Values.env.POSTGRES_HOST }}"
        - name: DB_NAME
          value: "{{ .Values.env.DB_NAME }}"
        - name: DB_USER
          value: "{{ .Values.env.DB_USER }}"
        - name: DB_PASSWORD
          value: "{{ .Values.env.DB_PASSWORD }}"
        volumeMounts:
            - name: efs-volume
              mountPath: {{ .Values.efs.mountPath }}
      volumes:
        - name: efs-volume
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-efs-pvc
