{{- if .Values.persistentVolume.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-pvc
spec:
  accessModes:
    {{- toYaml .Values.persistentVolume.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistentVolume.size }}
  storageClassName: {{ .Values.persistentVolume.storageClassName }}
{{- end }}
