apiVersion: v1
kind: Service
metadata:
  name: vote
spec:
  type: {{ .Values.service.type }}
  selector:
    app: vote
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 80
